/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaMenu */

#ifndef _Included_JavaMenu
#define _Included_JavaMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaMenu
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_JavaMenu_calculateSTDDev
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     JavaMenu
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_JavaMenu_calculateMean
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
